feat(feed): 피드 생성 Dialog 추가
cyclops-operation/switter pull request #23
Opened 2023-09-21 13:42 UTC by FRONT-JB

## 🛠️ 작업 내용 (Content)

> 작업 범위에 대해 간략하게 작성합니다.

- 피드 Dialog 추가
- Command UI 추가
- 피드 생성로직 추가

## 📝 상세 설명

> 리뷰어가 중점적으로 봐야 하는 부분을 바로 알 수 있도록 변경된 내용을 나열합니다.

- render props를 이용해 검색한 몬스터 정보에 대한 UI를 자유롭게 작성할 수 있도록 작성했습니다.

## ⚙️ 기타 사항

> PR에 대한 추가 설명이나 작업하면서 고민이 되었던 부분 등

- zod, react-hook-form으로 배열을 핸들링 하는 부분이 어려웠는데 [useFieldArray](https://react-hook-form.com/docs/usefieldarray)를 통해 쉽게 핸들링 할 수 있었습니다!

## 🚨 Merge 전 필요 작업 (Checklist before merge)

- [x] 컨벤션에 맞는 코드를 작성했나요?
- [x] 로컬 빌드시 에러가 발생하지 않았나요?

2023-09-21 14:47 UTC, FRONT-JB commented
@p-acid 에러가 발생하고나서 Dialog를 닫았다가 다시 열었을 때 이전 에러가 유지되는 현상을 추가로 수정했습니다.

2023-09-21 16:04 UTC, p-acid requested changes
수고하셨습니다! 추가적인 의견은 다음과 같습니다.

### UX

- 덱 몬스터 검색 후 선택을 할 때 선택 이후 화면에서 즉각적으로 변경 사항이 없어 선택이 되었는지 긴가민가 했던 것 같습니다. 선택 후, 어떤 몬스터가 선택되었는지 알려주거나 선택된 몬스터가 무엇인지 검색 목록에서 표시해주는 등의 UI 변화가 있으면 좋을 것 같습니다!

2023-09-21 16:04 UTC, p-acid commented on components/feed/feed-dialog.tsx
> +  })
확인했습니다!
반복적인 배열 관리 로직들을 많이 줄일 수 있겠네요. 좋은 메서드 알아갑니다 👍

2023-09-21 16:04 UTC, p-acid commented on lib/error-message.ts
> +  nickName: {
P1: 스펠링 수정 부탁드립니다!

```suggestion
  nickname: {
```

2023-09-21 16:04 UTC, p-acid commented on interface/monster.ts
> +      const monsterMap = new Map()
P4: `Map` 을 사용하신 이유가 있으실까요?

2023-09-21 16:04 UTC, p-acid commented on components/ui/command.tsx
> +import * as React from "react"
P4: 아직 활용되지 않는 컴포넌트 같은데 추후에 활용 예정인 컴포넌트인가요?

2023-09-21 16:38 UTC, FRONT-JB commented on interface/monster.ts
> +      const monsterMap = new Map()
배열의 중복을 제거하고 원본 배열과 길이가 같은지 체크하기 위해서 Map 객체를 사용했습니다!

2023-09-21 16:39 UTC, FRONT-JB commented on components/ui/command.tsx
> +import * as React from "react"
추후에 Role이 어드민인 경우에 유저관리를 위해 필요하다고 생각이 들어서 UI 컴포넌트를 추가했습니다!

2023-09-21 16:47 UTC, FRONT-JB commented on app/(auth)/feed/page.tsx
>  "use client"
수정했습니다!

2023-09-21 16:47 UTC, FRONT-JB commented on components/common/monster-image.tsx
> +  className?: string
수정했습니다!

2023-09-21 16:47 UTC, FRONT-JB commented on lib/error-message.ts
> +  nickName: {
수정했습니다! 밑에 guildName 이랑은 어떤 차이가 있는건가요?

2023-09-21 16:48 UTC, FRONT-JB commented
@p-acid 선택한 몬스터를 나타내는 화면은 어떻게 처리할지 다시 생각해보겠습니다! 수정사항 반영했습니다

2023-09-22 00:17 UTC, p-acid commented on lib/error-message.ts
> +  nickName: {
`nickname` 은 그 자체로 한 단어에 해당하고 `guildName` 은 `guild` 와 `name` 의 합성 형태로 알고 있어서 이렇게 바꿈이 좋다고 생각했습니다.

2023-09-22 00:18 UTC, p-acid commented
@FRONT-JB 전부 확인 완료했습니다.

2023-09-22 00:42 UTC, p-acid approved these changes
@FRONT-JB 전부 확인 완료했습니다.

2023-09-22 01:53 UTC, merged